#! /bin/bash
		#script ODD/EVEN esercizi su bash
if (( $# != 1 )) 	# il $# contiene il numero di argomenti che vengono passati dal utente, e il carattere $1 significa che è il primo argomento passato (in questo caso l'unico)
then
	echo "Devi immettere solo un argomento"

exit 1 #questo if serve a controllare quanti argomenti sono stati passati dall'utente e in caso di errore, a stampare in output l'errore
fi

arg=$1
c=1

if (( $arg + 0 )) 2> /dev/null  #ciclo che controlla se l'argomento è un numero primo o meno
then
	echo 
else
	echo "il numero non è un numero intero, errore" 
exit 1
fi

          #dichiaro la variabile c, che serve per il ciclo for e la variabile arg, variabile che prende il valore dell'argomento

if (( $arg < 0 ))     #controllo per far si che il valore sia un numero maggiore di 0 e di conseguenza accettabile dallo script
then
	echo "L'argomento deve essere un numero positivo"
exit 1
fi

for (( c; c<=arg; c++)) 	#ciclo for che viene svolto finche il contatore non possiede lo stesso valore di arg
do
if (( c % 2 == 0 ))   #if che stampa la variabile c, e a seconda del resto stabilisce se il numero è paro o disparo
then
	echo " $c è un numero pari"
else
	echo " $c è un numero dispari"
fi

done
