#!/bin/bash
read ip
ctr="(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])"     
if [[ $ip =~ ^$ctr\.$ctr\.$ctr\.$ctr$ ]]; then      #ciclo per stabilire se l'indirizzo ipv4 è valido
     echo "Indirizzo ipv4 valido:     "$ip
  
else
      echo "Indirizzo ipv4 non valido! "$ip
      exit 1
fi

a=$(echo "$ip" | cut -d'.' -f1)     #prendiamo una variabile che prende il primo ottetto, dell'indirizzo inserito in input.


if echo "$a" | grep -Eq "^(12[0-7]|1[01][0-9]|[1-9]?[0-9])$"; then   #tramite la variabile facciamo un if e i conseguenti elif, per stabilire la classe di appartenenza del ipv4.
echo " è un indirizzo di classe A"

elif echo "$a" | grep -Eq "^(12[89]|1[3-8][0-9]|19[01])$"; then
echo " è un indirizzo di classe B"

elif echo "$a" | grep -Eq "^19[2-9]|2[01][0-9]|22[0-3]$"; then
echo " è un indirizzo di classe C"

elif echo "$a" | grep -Eq "^22[4-9]|23[0-9]$"; then
echo " è un indirizzo di classe D"

elif echo "$a" | grep -Eq "^24[0-9]|25[0-5]$"; then
echo " è un indirizzo di classe E"

fi









