Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2204"

  config.vm.define "macchina1" do |nodo1|
    nodo1.vm.hostname = "macchina1"
    nodo1.vm.provision "shell", inline: <<-SHELL
 apt-get update -y
 apt-get install -y docker.io

 systemctl enable docker
 systemctl start docker
 usermod -aG docker vagrant
SHELL
  end

  config.vm.define "macchina2" do |nodo2|
    nodo2.vm.hostname = "macchina2"
    nodo2.vm.provision "shell", inline: <<-SHELL
 apt-get update -y
 apt-get install -y docker.io
 systemctl enable docker
 systemctl start docker

 usermod -aG docker vagrant
SHELL
	 
  end

   config.vm.provider "virtualbox" do |vb|
    vb.memory = 1024
    vb.cpus = 1
  end
end
