apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-storage-pv
spec:
  capacity:
    storage: 2Gi 
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany 
  persistentVolumeReclaimPolicy: Retain 
  storageClassName: manual-nfs
  nfs:
    server: 192.168.3.102  
    path: "/Volumes/nfs_data_share"  
    readOnly: false
