apiVersion: v1
kind: Pod
metadata:
  name: nfs-pod
spec:
  containers:
    - name: app-container
      image: busybox
      command: ["/bin/sh", "-c", "tail -f /dev/null"]
      volumeMounts:
        - name: nfs-volume
          mountPath: "/mnt/nfs"
  volumes:
    - name: nfs-volume
      nfs:
        server: 192.168.3.102 
        path: "/Users/pierluigi_cataoli/nfs" 
        readOnly: false
